### Importing Libraries

In [1]:
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd

pd.set_option('max_columns', None)

In [2]:
import findspark
findspark.init()

In [3]:
from pyspark.sql import SparkSession
spark = SparkSession.builder.master("local").appName("mySpark").getOrCreate()
sc = spark.sparkContext

In [4]:
def display(spark_dataframe, rows=5):
    """ shows the table contents in a readable format using pandas
    """

    return spark_dataframe.limit(rows).toPandas().head(rows);

### Import data/csv and Output sample csv

In [5]:
file = '../data/accepted_2007_to_2018Q4.csv'
file_type = file.split('.')[-1]

options = {
  'inferSchema': True,
  'header': True,
  'sep': ','
}

df = spark.read.format(file_type).options(**options).load(file)

In [6]:
# df.limit(10).write.format("csv").mode("overwrite").saveAsTable('LCD_Analysis_4excel')
filepath = '../output/LCD_Analysis_4excel.csv'
df.limit(10).toPandas().to_csv(filepath)

In [7]:
df = df.select('loan_amnt', 'funded_amnt', 'funded_amnt_inv', 'term', 'int_rate', 'installment', 'sub_grade', 'emp_title',\
               'emp_length', 'home_ownership', 'annual_inc', 'verification_status', 'loan_status', 'pymnt_plan', 'purpose',\
               'addr_state', 'dti', 'delinq_2yrs', 'fico_range_low', 'fico_range_high', 'inq_last_6mths', 'mths_since_last_delinq',\
               'open_acc', 'pub_rec', 'revol_bal', 'revol_util', 'total_acc', 'total_pymnt', 'total_pymnt_inv', 'total_rec_prncp',\
               'last_fico_range_high', 'last_fico_range_low', 'application_type', 'annual_inc_joint', 'dti_joint', 'verification_status_joint',\
               'acc_now_delinq', 'tot_coll_amt', 'tot_cur_bal', 'total_bal_il', 'il_util', 'max_bal_bc', 'all_util', 'total_rev_hi_lim',\
               'inq_fi', 'total_cu_tl', 'avg_cur_bal', 'bc_open_to_buy', 'bc_util', 'delinq_amnt', 'mort_acc', 'tot_hi_cred_lim',\
               'total_bal_ex_mort', 'total_bc_limit', 'total_il_high_credit_limit')
display(df)

,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,sub_grade,emp_title,emp_length,home_ownership,annual_inc,verification_status,loan_status,pymnt_plan,purpose,addr_state,dti,delinq_2yrs,fico_range_low,fico_range_high,inq_last_6mths,mths_since_last_delinq,open_acc,pub_rec,revol_bal,revol_util,total_acc,total_pymnt,total_pymnt_inv,total_rec_prncp,last_fico_range_high,last_fico_range_low,application_type,annual_inc_joint,dti_joint,verification_status_joint,acc_now_delinq,tot_coll_amt,tot_cur_bal,total_bal_il,il_util,max_bal_bc,all_util,total_rev_hi_lim,inq_fi,total_cu_tl,avg_cur_bal,bc_open_to_buy,bc_util,delinq_amnt,mort_acc,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit
0,3600.0,3600.0,3600.0,36 months,13.99,123.03,C4,leadman,10+ years,MORTGAGE,55000.0,Not Verified,Fully Paid,n,debt_consolidation,PA,5.91,0.0,675.0,679.0,1.0,30.0,7.0,0.0,2765.0,29.7,13.0,4421.723916800001,4421.72,3600.0,564.0,560.0,Individual,None,None,None,0.0,722.0,144904.0,4981.0,36.0,722.0,34.0,9300.0,3.0,1.0,20701.0,1506.0,37.2,0.0,1.0,178050.0,7746.0,2400.0,13734.0
1,24700.0,24700.0,24700.0,36 months,11.99,820.28,C1,Engineer,10+ years,MORTGAGE,65000.0,Not Verified,Fully Paid,n,small_business,SD,16.06,1.0,715.0,719.0,4.0,6.0,22.0,0.0,21470.0,19.2,38.0,25679.66,25679.66,24700.0,699.0,695.0,Individual,None,None,None,0.0,0.0,204396.0,18005.0,73.0,6472.0,29.0,111800.0,0.0,0.0,9733.0,57830.0,27.1,0.0,4.0,314017.0,39475.0,79300.0,24667.0
2,20000.0,20000.0,20000.0,60 months,10.78,432.66,B4,truck driver,10+ years,MORTGAGE,63000.0,Not Verified,Fully Paid,n,home_improvement,IL,10.78,0.0,695.0,699.0,0.0,None,6.0,0.0,7869.0,56.2,18.0,22705.924293878397,22705.92,20000.0,704.0,700.0,Joint App,71000.0,13.85,Not Verified,0.0,0.0,189699.0,10827.0,73.0,2081.0,65.0,14000.0,2.0,5.0,31617.0,2737.0,55.9,0.0,5.0,218418.0,18696.0,6200.0,14877.0
3,35000.0,35000.0,35000.0,60 months,14.85,829.90,C5,Information Systems Officer,10+ years,MORTGAGE,110000.0,Source Verified,Current,n,debt_consolidation,NJ,17.06,0.0,785.0,789.0,0.0,None,13.0,0.0,7802.0,11.6,17.0,31464.01,31464.01,19102.35,679.0,675.0,Individual,None,None,None,0.0,0.0,301500.0,12609.0,70.0,6987.0,45.0,67300.0,0.0,1.0,23192.0,54962.0,12.1,0.0,1.0,381215.0,52226.0,62500.0,18000.0
4,10400.0,10400.0,10400.0,60 months,22.45,289.91,F1,Contract Specialist,3 years,MORTGAGE,104433.0,Source Verified,Fully Paid,n,major_purchase,PA,25.37,1.0,695.0,699.0,3.0,12.0,12.0,0.0,21929.0,64.5,35.0,11740.5,11740.5,10400.0,704.0,700.0,Individual,None,None,None,0.0,0.0,331730.0,73839.0,84.0,9702.0,78.0,34000.0,2.0,1.0,27644.0,4567.0,77.5,0.0,6.0,439570.0,95768.0,20300.0,88097.0

### pre-processing the columns

Part 1: Remove Text
some columns need text to be removed from the data:
term, emp_length

some columns

#### Part 1: Remove Text

In [8]:
from pyspark.sql.functions import regexp_extract, col

In [9]:
df = df.withColumn('term_months', regexp_extract(col('term'), r'\d+', 0))
display(df)

,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,sub_grade,emp_title,emp_length,home_ownership,annual_inc,verification_status,loan_status,pymnt_plan,purpose,addr_state,dti,delinq_2yrs,fico_range_low,fico_range_high,inq_last_6mths,mths_since_last_delinq,open_acc,pub_rec,revol_bal,revol_util,total_acc,total_pymnt,total_pymnt_inv,total_rec_prncp,last_fico_range_high,last_fico_range_low,application_type,annual_inc_joint,dti_joint,verification_status_joint,acc_now_delinq,tot_coll_amt,tot_cur_bal,total_bal_il,il_util,max_bal_bc,all_util,total_rev_hi_lim,inq_fi,total_cu_tl,avg_cur_bal,bc_open_to_buy,bc_util,delinq_amnt,mort_acc,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit,term_months
0,3600.0,3600.0,3600.0,36 months,13.99,123.03,C4,leadman,10+ years,MORTGAGE,55000.0,Not Verified,Fully Paid,n,debt_consolidation,PA,5.91,0.0,675.0,679.0,1.0,30.0,7.0,0.0,2765.0,29.7,13.0,4421.723916800001,4421.72,3600.0,564.0,560.0,Individual,None,None,None,0.0,722.0,144904.0,4981.0,36.0,722.0,34.0,9300.0,3.0,1.0,20701.0,1506.0,37.2,0.0,1.0,178050.0,7746.0,2400.0,13734.0,36
1,24700.0,24700.0,24700.0,36 months,11.99,820.28,C1,Engineer,10+ years,MORTGAGE,65000.0,Not Verified,Fully Paid,n,small_business,SD,16.06,1.0,715.0,719.0,4.0,6.0,22.0,0.0,21470.0,19.2,38.0,25679.66,25679.66,24700.0,699.0,695.0,Individual,None,None,None,0.0,0.0,204396.0,18005.0,73.0,6472.0,29.0,111800.0,0.0,0.0,9733.0,57830.0,27.1,0.0,4.0,314017.0,39475.0,79300.0,24667.0,36
2,20000.0,20000.0,20000.0,60 months,10.78,432.66,B4,truck driver,10+ years,MORTGAGE,63000.0,Not Verified,Fully Paid,n,home_improvement,IL,10.78,0.0,695.0,699.0,0.0,None,6.0,0.0,7869.0,56.2,18.0,22705.924293878397,22705.92,20000.0,704.0,700.0,Joint App,71000.0,13.85,Not Verified,0.0,0.0,189699.0,10827.0,73.0,2081.0,65.0,14000.0,2.0,5.0,31617.0,2737.0,55.9,0.0,5.0,218418.0,18696.0,6200.0,14877.0,60
3,35000.0,35000.0,35000.0,60 months,14.85,829.90,C5,Information Systems Officer,10+ years,MORTGAGE,110000.0,Source Verified,Current,n,debt_consolidation,NJ,17.06,0.0,785.0,789.0,0.0,None,13.0,0.0,7802.0,11.6,17.0,31464.01,31464.01,19102.35,679.0,675.0,Individual,None,None,None,0.0,0.0,301500.0,12609.0,70.0,6987.0,45.0,67300.0,0.0,1.0,23192.0,54962.0,12.1,0.0,1.0,381215.0,52226.0,62500.0,18000.0,60
4,10400.0,10400.0,10400.0,60 months,22.45,289.91,F1,Contract Specialist,3 years,MORTGAGE,104433.0,Source Verified,Fully Paid,n,major_purchase,PA,25.37,1.0,695.0,699.0,3.0,12.0,12.0,0.0,21929.0,64.5,35.0,11740.5,11740.5,10400.0,704.0,700.0,Individual,None,None,None,0.0,0.0,331730.0,73839.0,84.0,9702.0,78.0,34000.0,2.0,1.0,27644.0,4567.0,77.5,0.0,6.0,439570.0,95768.0,20300.0,88097.0,60

In [10]:
df.select('term', 'term_months').show(10)

+----------+-----------+
|      term|term_months|
+----------+-----------+
| 36 months|         36|
| 36 months|         36|
| 60 months|         60|
| 60 months|         60|
| 60 months|         60|
| 36 months|         36|
| 36 months|         36|
| 36 months|         36|
| 36 months|         36|
| 36 months|         36|
+----------+-----------+
only showing top 10 rows

In [11]:
df = df.withColumn('emp_length_years', regexp_extract(col('emp_length'),r'\d+', 0))
display(df)

,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,sub_grade,emp_title,emp_length,home_ownership,annual_inc,verification_status,loan_status,pymnt_plan,purpose,addr_state,dti,delinq_2yrs,fico_range_low,fico_range_high,inq_last_6mths,mths_since_last_delinq,open_acc,pub_rec,revol_bal,revol_util,total_acc,total_pymnt,total_pymnt_inv,total_rec_prncp,last_fico_range_high,last_fico_range_low,application_type,annual_inc_joint,dti_joint,verification_status_joint,acc_now_delinq,tot_coll_amt,tot_cur_bal,total_bal_il,il_util,max_bal_bc,all_util,total_rev_hi_lim,inq_fi,total_cu_tl,avg_cur_bal,bc_open_to_buy,bc_util,delinq_amnt,mort_acc,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit,term_months,emp_length_years
0,3600.0,3600.0,3600.0,36 months,13.99,123.03,C4,leadman,10+ years,MORTGAGE,55000.0,Not Verified,Fully Paid,n,debt_consolidation,PA,5.91,0.0,675.0,679.0,1.0,30.0,7.0,0.0,2765.0,29.7,13.0,4421.723916800001,4421.72,3600.0,564.0,560.0,Individual,None,None,None,0.0,722.0,144904.0,4981.0,36.0,722.0,34.0,9300.0,3.0,1.0,20701.0,1506.0,37.2,0.0,1.0,178050.0,7746.0,2400.0,13734.0,36,10
1,24700.0,24700.0,24700.0,36 months,11.99,820.28,C1,Engineer,10+ years,MORTGAGE,65000.0,Not Verified,Fully Paid,n,small_business,SD,16.06,1.0,715.0,719.0,4.0,6.0,22.0,0.0,21470.0,19.2,38.0,25679.66,25679.66,24700.0,699.0,695.0,Individual,None,None,None,0.0,0.0,204396.0,18005.0,73.0,6472.0,29.0,111800.0,0.0,0.0,9733.0,57830.0,27.1,0.0,4.0,314017.0,39475.0,79300.0,24667.0,36,10
2,20000.0,20000.0,20000.0,60 months,10.78,432.66,B4,truck driver,10+ years,MORTGAGE,63000.0,Not Verified,Fully Paid,n,home_improvement,IL,10.78,0.0,695.0,699.0,0.0,None,6.0,0.0,7869.0,56.2,18.0,22705.924293878397,22705.92,20000.0,704.0,700.0,Joint App,71000.0,13.85,Not Verified,0.0,0.0,189699.0,10827.0,73.0,2081.0,65.0,14000.0,2.0,5.0,31617.0,2737.0,55.9,0.0,5.0,218418.0,18696.0,6200.0,14877.0,60,10
3,35000.0,35000.0,35000.0,60 months,14.85,829.90,C5,Information Systems Officer,10+ years,MORTGAGE,110000.0,Source Verified,Current,n,debt_consolidation,NJ,17.06,0.0,785.0,789.0,0.0,None,13.0,0.0,7802.0,11.6,17.0,31464.01,31464.01,19102.35,679.0,675.0,Individual,None,None,None,0.0,0.0,301500.0,12609.0,70.0,6987.0,45.0,67300.0,0.0,1.0,23192.0,54962.0,12.1,0.0,1.0,381215.0,52226.0,62500.0,18000.0,60,10
4,10400.0,10400.0,10400.0,60 months,22.45,289.91,F1,Contract Specialist,3 years,MORTGAGE,104433.0,Source Verified,Fully Paid,n,major_purchase,PA,25.37,1.0,695.0,699.0,3.0,12.0,12.0,0.0,21929.0,64.5,35.0,11740.5,11740.5,10400.0,704.0,700.0,Individual,None,None,None,0.0,0.0,331730.0,73839.0,84.0,9702.0,78.0,34000.0,2.0,1.0,27644.0,4567.0,77.5,0.0,6.0,439570.0,95768.0,20300.0,88097.0,60,3

In [12]:
df.select('emp_length', 'emp_length_years').show()

+----------+----------------+
|emp_length|emp_length_years|
+----------+----------------+
| 10+ years|              10|
| 10+ years|              10|
| 10+ years|              10|
| 10+ years|              10|
|   3 years|               3|
|   4 years|               4|
| 10+ years|              10|
| 10+ years|              10|
|   6 years|               6|
| 10+ years|              10|
|   6 years|               6|
|    1 year|               1|
|   3 years|               3|
|   7 years|               7|
| 10+ years|              10|
|   8 years|               8|
| 10+ years|              10|
| 10+ years|              10|
|   5 years|               5|
|   8 years|               8|
+----------+----------------+
only showing top 20 rows

In [13]:
df.select('dti', 'dti_joint').show(10)

+-----+---------+
|  dti|dti_joint|
+-----+---------+
| 5.91|     null|
|16.06|     null|
|10.78|    13.85|
|17.06|     null|
|25.37|     null|
| 10.2|     null|
|14.67|     null|
|17.61|     null|
|13.07|     null|
| 34.8|     null|
+-----+---------+
only showing top 10 rows

In [14]:
from pyspark.sql.functions import coalesce, isnull

In [15]:
df.select('dti', 'dti_joint', coalesce(col('dti_joint'), col('dti'))).show(10)

+-----+---------+------------------------+
|  dti|dti_joint|coalesce(dti_joint, dti)|
+-----+---------+------------------------+
| 5.91|     null|                    5.91|
|16.06|     null|                   16.06|
|10.78|    13.85|                   13.85|
|17.06|     null|                   17.06|
|25.37|     null|                   25.37|
| 10.2|     null|                    10.2|
|14.67|     null|                   14.67|
|17.61|     null|                   17.61|
|13.07|     null|                   13.07|
| 34.8|     null|                    34.8|
+-----+---------+------------------------+
only showing top 10 rows

In [16]:
df = df.withColumn('dti_joint_merged', coalesce(col('dti_joint'), col('dti')))
display(df)

,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,sub_grade,emp_title,emp_length,home_ownership,annual_inc,verification_status,loan_status,pymnt_plan,purpose,addr_state,dti,delinq_2yrs,fico_range_low,fico_range_high,inq_last_6mths,mths_since_last_delinq,open_acc,pub_rec,revol_bal,revol_util,total_acc,total_pymnt,total_pymnt_inv,total_rec_prncp,last_fico_range_high,last_fico_range_low,application_type,annual_inc_joint,dti_joint,verification_status_joint,acc_now_delinq,tot_coll_amt,tot_cur_bal,total_bal_il,il_util,max_bal_bc,all_util,total_rev_hi_lim,inq_fi,total_cu_tl,avg_cur_bal,bc_open_to_buy,bc_util,delinq_amnt,mort_acc,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit,term_months,emp_length_years,dti_joint_merged
0,3600.0,3600.0,3600.0,36 months,13.99,123.03,C4,leadman,10+ years,MORTGAGE,55000.0,Not Verified,Fully Paid,n,debt_consolidation,PA,5.91,0.0,675.0,679.0,1.0,30.0,7.0,0.0,2765.0,29.7,13.0,4421.723916800001,4421.72,3600.0,564.0,560.0,Individual,None,None,None,0.0,722.0,144904.0,4981.0,36.0,722.0,34.0,9300.0,3.0,1.0,20701.0,1506.0,37.2,0.0,1.0,178050.0,7746.0,2400.0,13734.0,36,10,5.91
1,24700.0,24700.0,24700.0,36 months,11.99,820.28,C1,Engineer,10+ years,MORTGAGE,65000.0,Not Verified,Fully Paid,n,small_business,SD,16.06,1.0,715.0,719.0,4.0,6.0,22.0,0.0,21470.0,19.2,38.0,25679.66,25679.66,24700.0,699.0,695.0,Individual,None,None,None,0.0,0.0,204396.0,18005.0,73.0,6472.0,29.0,111800.0,0.0,0.0,9733.0,57830.0,27.1,0.0,4.0,314017.0,39475.0,79300.0,24667.0,36,10,16.06
2,20000.0,20000.0,20000.0,60 months,10.78,432.66,B4,truck driver,10+ years,MORTGAGE,63000.0,Not Verified,Fully Paid,n,home_improvement,IL,10.78,0.0,695.0,699.0,0.0,None,6.0,0.0,7869.0,56.2,18.0,22705.924293878397,22705.92,20000.0,704.0,700.0,Joint App,71000.0,13.85,Not Verified,0.0,0.0,189699.0,10827.0,73.0,2081.0,65.0,14000.0,2.0,5.0,31617.0,2737.0,55.9,0.0,5.0,218418.0,18696.0,6200.0,14877.0,60,10,13.85
3,35000.0,35000.0,35000.0,60 months,14.85,829.90,C5,Information Systems Officer,10+ years,MORTGAGE,110000.0,Source Verified,Current,n,debt_consolidation,NJ,17.06,0.0,785.0,789.0,0.0,None,13.0,0.0,7802.0,11.6,17.0,31464.01,31464.01,19102.35,679.0,675.0,Individual,None,None,None,0.0,0.0,301500.0,12609.0,70.0,6987.0,45.0,67300.0,0.0,1.0,23192.0,54962.0,12.1,0.0,1.0,381215.0,52226.0,62500.0,18000.0,60,10,17.06
4,10400.0,10400.0,10400.0,60 months,22.45,289.91,F1,Contract Specialist,3 years,MORTGAGE,104433.0,Source Verified,Fully Paid,n,major_purchase,PA,25.37,1.0,695.0,699.0,3.0,12.0,12.0,0.0,21929.0,64.5,35.0,11740.5,11740.5,10400.0,704.0,700.0,Individual,None,None,None,0.0,0.0,331730.0,73839.0,84.0,9702.0,78.0,34000.0,2.0,1.0,27644.0,4567.0,77.5,0.0,6.0,439570.0,95768.0,20300.0,88097.0,60,3,25.37